"""
proposal_data.py
----------------
Shared data structures for The Benefits Group proposal generator.
Edit this file to add new clients or plans, then run:
  python generate_pdf.py
  python generate_excel.py
"""

# ── CLIENT / EMPLOYER INFO ────────────────────────────────────────────────────

CLIENT = {
    "name":               "TennGreen Land Conservancy",
    "address":            "1213 16th Ave South",
    "city_state_zip":     "Nashville, TN. 37212",
    "county":             "Davidson",
    "sic_code":           "9512",
    "quote_id":           "NB46F5F",
    "effective_date":     "August 1, 2026",
    "effective_date_mmddyyyy": "08/01/2026",
    "total_employees":    15,
    "eligible_employees": 15,
    "enrolling_employees":15,
    "waiving_employees":  0,
    "total_dependents":   0,
    # Coverage tiers (EE=employee only, ES=+spouse, EC=+children, EF=family)
    "tier_ee": 15, "tier_es": 0, "tier_ec": 0, "tier_ef": 0,
}

PRODUCER = {
    "agency":    "The Benefits Group",
    "sub_agency":"Solutionpoint Consulting",
    "phone":     "(615) 560-3667",
    "email":     "happy@benefits.place",
}

CONTRIBUTIONS = {
    "medical_ee":  "50%", "medical_dep": "0%",
    "dental_ee":   "0%",  "dental_dep":  "0%",
    "vision_ee":   "0%",  "vision_dep":  "0%",
    "life":        "100% employee only",
}

# ── MEDICAL PLANS ─────────────────────────────────────────────────────────────
# Each dict = one plan card. Add/remove dicts to control what's in the proposal.
# "include": False to skip a plan without deleting it.

MEDICAL_PLANS = [
    {
        "include": True,
        "rank": 1,
        "carrier": "PHCS/RBP",
        "plan_name": "PHCS/RBP $5000 RBP Renewal Affinity Benefit Solutions",
        "network": "PHCS/RBP",
        "plan_type": "PPO",
        "funding": "Level Funding",
        "quote_type": "Underwritten Quote",
        "deductible_in_ind": "$5,000",  "deductible_in_fam": "$10,000",
        "deductible_out_ind": "/",      "deductible_out_fam": "/",
        "oop_in_ind": "$6,500",         "oop_in_fam": "$13,100",
        "oop_out_ind": "/",             "oop_out_fam": "/",
        "coinsurance_in": "20%",        "coinsurance_out": "See SBC",
        "doctor_visit": "Deductible Coinsurance",
        "virtual_visit": "See SBC",
        "specialist": "Deductible Coinsurance",
        "xray_lab": "Deductible Coinsurance",
        "imaging": "Deductible Coinsurance",
        "urgent_care": "Deductible Coinsurance",
        "er": "Deductible Coinsurance",
        "hospital": "Deductible Coinsurance",
        "rx": "Deductible then $15 / $65 / $100",
        "rx_deductible": "See SBC",
        "hsa_eligible": False,
        "rate_ee": 438.99,  "rate_es": 877.18,
        "rate_ec": 789.54,  "rate_ef": 1315.38,
        "employer_cost": 3292.50, "employee_cost": 3292.35,
        "monthly_premium": 6584.85,
    },
    {
        "include": True,
        "rank": 2,
        "carrier": "Cigna",
        "plan_name": "Cigna $5000 HSA Renewal Affinity Benefit Solutions",
        "network": "Cigna",
        "plan_type": "PPO",
        "funding": "Level Funding",
        "quote_type": "Underwritten Quote",
        "deductible_in_ind": "$5,000",  "deductible_in_fam": "$10,000",
        "deductible_out_ind": "/",      "deductible_out_fam": "/",
        "oop_in_ind": "$6,550",         "oop_in_fam": "$13,100",
        "oop_out_ind": "/",             "oop_out_fam": "/",
        "coinsurance_in": "20%",        "coinsurance_out": "See SBC",
        "doctor_visit": "Deductible Coinsurance",
        "virtual_visit": "See SBC",
        "specialist": "Deductible Coinsurance",
        "xray_lab": "Deductible Coinsurance",
        "imaging": "Deductible Coinsurance",
        "urgent_care": "Deductible Coinsurance",
        "er": "Deductible Coinsurance",
        "hospital": "Deductible Coinsurance",
        "rx": "Deductible then $15 / $65 / $100",
        "rx_deductible": "See SBC",
        "hsa_eligible": True,
        "rate_ee": 504.72,  "rate_es": 1008.64,
        "rate_ec": 907.85,  "rate_ef": 1512.57,
        "employer_cost": 3785.40, "employee_cost": 3785.40,
        "monthly_premium": 7570.80,
    },
    {
        "include": True,
        "rank": 3,
        "carrier": "PHCS/RBP",
        "plan_name": "PHCS/RBP $3500 RBP Renewal Affinity Benefit Solutions",
        "network": "PHCS/RBP",
        "plan_type": "PPO",
        "funding": "Level Funding",
        "quote_type": "Underwritten Quote",
        "deductible_in_ind": "$3,500",  "deductible_in_fam": "$7,000",
        "deductible_out_ind": "/",      "deductible_out_fam": "/",
        "oop_in_ind": "$7,350",         "oop_in_fam": "$14,700",
        "oop_out_ind": "/",             "oop_out_fam": "/",
        "coinsurance_in": "20%",        "coinsurance_out": "See SBC",
        "doctor_visit": "$45",
        "virtual_visit": "See SBC",
        "specialist": "$90",
        "xray_lab": "Deductible Coinsurance",
        "imaging": "Deductible Coinsurance",
        "urgent_care": "$90",
        "er": "Deductible Coinsurance",
        "hospital": "Deductible Coinsurance",
        "rx": "$15 / $65 / $100",
        "rx_deductible": "See SBC",
        "hsa_eligible": False,
        "rate_ee": 520.69,  "rate_es": 1037.61,
        "rate_ec": 934.23,  "rate_ef": 1554.55,
        "employer_cost": 3905.25, "employee_cost": 3905.10,
        "monthly_premium": 7810.35,
    },
    {
        "include": True,
        "rank": 4,
        "carrier": "Cigna",
        "plan_name": "Cigna NAV $5000",
        "network": "Cigna",
        "plan_type": "PPO",
        "funding": "Level Funding",
        "quote_type": "Underwritten Quote",
        "deductible_in_ind": "$5,000",  "deductible_in_fam": "$10,000",
        "deductible_out_ind": "/",      "deductible_out_fam": "/",
        "oop_in_ind": "$5,000",         "oop_in_fam": "$10,000",
        "oop_out_ind": "/",             "oop_out_fam": "/",
        "coinsurance_in": "0%",         "coinsurance_out": "See SBC",
        "doctor_visit": "Deductible Coinsurance",
        "virtual_visit": "See SBC",
        "specialist": "Deductible Coinsurance",
        "xray_lab": "Deductible Coinsurance",
        "imaging": "Deductible Coinsurance",
        "urgent_care": "Deductible Coinsurance",
        "er": "Deductible Coinsurance",
        "hospital": "Deductible Coinsurance",
        "rx": "Deductible Coinsurance",
        "rx_deductible": "See SBC",
        "hsa_eligible": False,
        "rate_ee": 441.13,  "rate_es": 1062.90,
        "rate_ec": 822.22,  "rate_ef": 1363.76,
        "employer_cost": 3308.55, "employee_cost": 3308.40,
        "monthly_premium": 6616.95,
    },
    {
        "include": True,
        "rank": 5,
        "carrier": "Cigna",
        "plan_name": "Cigna NAV $5000 HSA",
        "network": "Cigna",
        "plan_type": "PPO",
        "funding": "Level Funding",
        "quote_type": "Underwritten Quote",
        "deductible_in_ind": "$5,000",  "deductible_in_fam": "$10,000",
        "deductible_out_ind": "/",      "deductible_out_fam": "/",
        "oop_in_ind": "$5,000",         "oop_in_fam": "$10,000",
        "oop_out_ind": "/",             "oop_out_fam": "/",
        "coinsurance_in": "0%",         "coinsurance_out": "See SBC",
        "doctor_visit": "Deductible Coinsurance",
        "virtual_visit": "See SBC",
        "specialist": "Deductible Coinsurance",
        "xray_lab": "Deductible Coinsurance",
        "imaging": "Deductible Coinsurance",
        "urgent_care": "Deductible Coinsurance",
        "er": "Deductible Coinsurance",
        "hospital": "Deductible Coinsurance",
        "rx": "Deductible Coinsurance",
        "rx_deductible": "See SBC",
        "hsa_eligible": True,
        "rate_ee": 494.39,  "rate_es": 850.83,
        "rate_ec": 861.63,  "rate_ef": 1144.63,
        "employer_cost": 3708.00, "employee_cost": 3707.85,
        "monthly_premium": 7415.85,
    },
    {
        "include": True,
        "rank": 6,
        "carrier": "Cigna",
        "plan_name": "Cigna $3500 Cigna Renewal Affinity Benefit Solutions",
        "network": "Cigna",
        "plan_type": "PPO",
        "funding": "Level Funding",
        "quote_type": "Underwritten Quote",
        "deductible_in_ind": "$3,500",  "deductible_in_fam": "$7,000",
        "deductible_out_ind": "/",      "deductible_out_fam": "/",
        "oop_in_ind": "$7,350",         "oop_in_fam": "$14,700",
        "oop_out_ind": "/",             "oop_out_fam": "/",
        "coinsurance_in": "20%",        "coinsurance_out": "See SBC",
        "doctor_visit": "$45",
        "virtual_visit": "See SBC",
        "specialist": "$90",
        "xray_lab": "Deductible Coinsurance",
        "imaging": "Deductible Coinsurance",
        "urgent_care": "$90",
        "er": "Deductible Coinsurance",
        "hospital": "Deductible Coinsurance",
        "rx": "$15 / $65 / $100",
        "rx_deductible": "See SBC",
        "hsa_eligible": False,
        "rate_ee": 598.23,  "rate_es": 1192.69,
        "rate_ec": 1073.80, "rate_ef": 1787.17,
        "employer_cost": 4486.80, "employee_cost": 4486.65,
        "monthly_premium": 8973.45,
    },
]

# ── DENTAL PLANS ──────────────────────────────────────────────────────────────

DENTAL_PLANS = [
    {
        "include": True,
        "rank": 1,
        "carrier": "Beam",
        "plan_name": "Beam Smart Premium Plus 100/80/50-1000",
        "plan_type": "PPO",
        "deductible_in_ind": "$50",  "deductible_in_fam": "$150",
        "deductible_out": "See SBC",
        "annual_max_in": "$1,000",   "annual_max_out": "See SBC",
        "preventive": "100%",  "basic": "80%",   "major": "50%",
        "ortho_max": "Not Covered",
        "endodontics": "80%",  "simple_extractions": "See SBC",
        "implants": "Covered", "periodontics": "80%",
        "oral_surgery": "See SBC", "composite_filling": "Covered",
        "waive_preventive_max": "Unknown",
        "rate_ee": 31.39,  "rate_es": 62.79,
        "rate_ec": 70.97,  "rate_ef": 102.36,
        "employer_cost": 0.00, "employee_cost": 470.85,
        "monthly_premium": 470.85,
    },
    {
        "include": True,
        "rank": 2,
        "carrier": "Beam",
        "plan_name": "Beam Smart Premium Select 100/90/60-2000",
        "plan_type": "PPO",
        "deductible_in_ind": "$50",  "deductible_in_fam": "$150",
        "deductible_out": "See SBC",
        "annual_max_in": "$2,000",   "annual_max_out": "See SBC",
        "preventive": "100%",  "basic": "90%",   "major": "60%",
        "ortho_max": "Not Covered",
        "endodontics": "90%",  "simple_extractions": "See SBC",
        "implants": "Covered", "periodontics": "90%",
        "oral_surgery": "See SBC", "composite_filling": "Covered",
        "waive_preventive_max": "Unknown",
        "rate_ee": 40.27,  "rate_es": 80.54,
        "rate_ec": 84.60,  "rate_ef": 124.87,
        "employer_cost": 0.00, "employee_cost": 604.05,
        "monthly_premium": 604.05,
    },
    {
        "include": True,
        "rank": 3,
        "carrier": "Beam",
        "plan_name": "Beam Smart Premium Ultra 100/100/60-5000",
        "plan_type": "PPO",
        "deductible_in_ind": "$25",  "deductible_in_fam": "$75",
        "deductible_out": "See SBC",
        "annual_max_in": "$5,000",   "annual_max_out": "See SBC",
        "preventive": "100%",  "basic": "100%",  "major": "60%",
        "ortho_max": "Not Covered",
        "endodontics": "100%", "simple_extractions": "See SBC",
        "implants": "Covered", "periodontics": "100%",
        "oral_surgery": "See SBC", "composite_filling": "Covered",
        "waive_preventive_max": "Unknown",
        "rate_ee": 46.70,  "rate_es": 93.40,
        "rate_ec": 94.54,  "rate_ef": 141.25,
        "employer_cost": 0.00, "employee_cost": 700.50,
        "monthly_premium": 700.50,
    },
]

# ── VISION PLANS ──────────────────────────────────────────────────────────────

VISION_PLANS = [
    {
        "include": True,
        "rank": 1,
        "carrier": "Beam",
        "plan_name": "Beam VSP Choice Plan #5",
        "plan_type": "PPO",
        "exam_frequency": "12 months / $10",
        "lenses_frequency": "12 months / $130",
        "frames_frequency": "24 months / $130",
        "contacts_frequency": "See SBC",
        "rate_ee": 7.69,   "rate_es": 15.49,
        "rate_ec": 16.41,  "rate_ef": 25.74,
        "employer_cost": 0.00, "employee_cost": 115.35,
        "monthly_premium": 115.35,
    },
    {
        "include": True,
        "rank": 2,
        "carrier": "Beam",
        "plan_name": "Beam VSP Choice Plan #2",
        "plan_type": "PPO",
        "exam_frequency": "12 months / $10",
        "lenses_frequency": "12 months / $150",
        "frames_frequency": "12 months / $150",
        "contacts_frequency": "See SBC",
        "rate_ee": 9.04,   "rate_es": 18.16,
        "rate_ec": 19.01,  "rate_ef": 29.87,
        "employer_cost": 0.00, "employee_cost": 135.60,
        "monthly_premium": 135.60,
    },
    {
        "include": True,
        "rank": 3,
        "carrier": "Beam",
        "plan_name": "Beam VSP Choice Plan #3",
        "plan_type": "PPO",
        "exam_frequency": "12 months / $10",
        "lenses_frequency": "12 months / $200",
        "frames_frequency": "12 months / $200",
        "contacts_frequency": "See SBC",
        "rate_ee": 10.55,  "rate_es": 21.26,
        "rate_ec": 22.07,  "rate_ef": 34.79,
        "employer_cost": 0.00, "employee_cost": 158.25,
        "monthly_premium": 158.25,
    },
]

DISCLAIMER_TEXT = """The above rates and benefits are for general information and discussion purposes only and not valid unless approved by the carrier. This rate quote is not an offer or a guarantee of coverage. The rates quoted are applicable to the plan design selected. Actual costs will vary based on factors such as the case characteristics of the group and/or employees/dependents to be insured, the insurance plan selected and the start date. Rates are determined by the carrier and are not final until the group is enrolled with the carrier. This group should not, under any circumstances, cancel its existing coverage unless and until coverage is offered by the carrier and final rates have been accepted by and initial premium paid by the group.

Beam: Dental and vision insurance products underwritten by National Guardian Life Insurance Company (NGL), Madison, WI, marketed by Beam Insurance Services LLC. All above rates and benefits are for general information and discussion only. Rates are determined by the carrier and are not final until the group is enrolled with the carrier."""
